### ISSUE TITLE
Website reporting failure when it should not for custom tests.

### ISSUE THREAD

**Issue by kotp** [exercism/ruby#1226]
@iHiD https://exercism.org/tracks/ruby/exercises/hello-world/iterations?idx=6 reports that the tests are unable to complete for some reason, but does not expose exactly why. It should run in the current versions of Ruby,  But hard to see what is happening, for what is reported.

![image](https://user-images.githubusercontent.com/16747/133897960-2dee305b-f69c-4af0-8f1e-54c66aa5a84f.png)

The code and the report.

From the web editor way of doing things:

![image](https://user-images.githubusercontent.com/16747/133898012-1273e131-a984-46f9-b94f-8dbe443e3511.png)

**Comment by iHiD** [comment]
This should now be fixed.

**Comment by kotp** [comment]
I checked, and running the test again (even after deleting the second file and placing that code in `hello_world.rb` on the web editor) still fails.

**Comment by kotp** [comment]
![image](https://user-images.githubusercontent.com/16747/134424167-c9fecb35-25bb-4d1c-8b15-d36b54110a6e.png)

To show the result that I am seeing…

**Comment by iHiD** [comment]
OK, I hadn't appreciated what you are doing here.

Yeah, we require various extra metadata for custom tests, which you're not able to provide this way. The tests couldn't show in the website without it. So the Ruby Test Runner breaks when generating the output. 

I don't really see this as a bug - we can't account for all the possible variants of what people could do - only the things we expect, and overriding minitest doesn't sit in my "normal behaviour" category.

**Comment by iHiD** [comment]
For your reference this is the error within the test runner.

```/opt/test-runner/lib/minitest_ext/exercism_reporter.rb:106:in `index': undefined method `[]' for nil:NilClass (NoMethodError)
	from /opt/test-runner/lib/minitest_ext/exercism_reporter.rb:30:in `each'
	from /opt/test-runner/lib/minitest_ext/exercism_reporter.rb:30:in `sort_by'
	from /opt/test-runner/lib/minitest_ext/exercism_reporter.rb:30:in `report'
	from /usr/local/bundle/gems/minitest-5.11.3/lib/minitest.rb:808:in `each'
	from /usr/local/bundle/gems/minitest-5.11.3/lib/minitest.rb:808:in `report'
	from /usr/local/bundle/gems/minitest-5.11.3/lib/minitest.rb:141:in `run'
	from /usr/local/bundle/gems/minitest-5.11.3/lib/minitest.rb:63:in `block in autorun'```
